name: Build and deploy Next.js app to Azure Web App - azure-ad-nejma

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies and build the app
      - name: Install dependencies and build Next.js
        run: |
          npm install
          npm run build
        env:
          NODE_ENV: production

      # Zip necessary files, including .next folder
      - name: Zip artifact for deployment
        run: zip -r release.zip .next public package.json node_modules

      # Upload the artifact for the deployment job
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      # Unzip the artifact for deployment
      - name: Unzip artifact
        run: unzip release.zip

      # Login to Azure using credentials
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6E8C6B2A230C494B9EBE0476D15EECA9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0A32FBF67DE6418E810D983BA65078A7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3EA88DC4E9348C6BBC1AD84DDB7EAB9 }}

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'azure-ad-nejma'
          slot-name: 'production'
          package: .
